//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Qoollo.MpegDash
{
    using System.Xml.Serialization;
    using System.CodeDom.Compiler;
    using System;
    using System.Diagnostics;
    using System.ComponentModel;
    using System.Xml;


    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    [XmlRootAttribute("MPD", Namespace = "urn:mpeg:dash:schema:mpd:2011", IsNullable = false)]
    public partial class MPD
    {

        private ProgramInformationType[] programInformation;

        private BaseURLType[] baseURL;

        private string[] location;

        private PeriodType[] period;

        private MetricsType[] metrics;

        private DescriptorType[] essentialProperty;

        private DescriptorType[] supplementalProperty;

        private DescriptorType[] uTCTiming;

        private System.Xml.XmlElement[] any;

        private string id;

        private string profiles;

        private PresentationType type;

        private DateTime availabilityStartTime;

        private bool availabilityStartTimeFieldSpecified;

        private DateTime availabilityEndTime;

        private bool availabilityEndTimeFieldSpecified;

        private DateTime publishTime;

        private bool publishTimeFieldSpecified;

        private string mediaPresentationDuration;

        private string minimumUpdatePeriod;

        private string minBufferTime;

        private string timeShiftBufferDepth;

        private string suggestedPresentationDelay;

        private string maxSegmentDuration;

        private string maxSubsegmentDuration;

        private System.Xml.XmlAttribute[] anyAttr;

        public MPD()
        {
            this.type = PresentationType.@static;
        }

        /// <remarks/>
        [XmlElementAttribute("ProgramInformation")]
        public ProgramInformationType[] ProgramInformation
        {
            get
            {
                return this.programInformation;
            }
            set
            {
                this.programInformation = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL
        {
            get
            {
                return this.baseURL;
            }
            set
            {
                this.baseURL = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Location", DataType = "anyURI")]
        public string[] Location
        {
            get
            {
                return this.location;
            }
            set
            {
                this.location = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Period")]
        public PeriodType[] Period
        {
            get
            {
                return this.period;
            }
            set
            {
                this.period = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Metrics")]
        public MetricsType[] Metrics
        {
            get
            {
                return this.metrics;
            }
            set
            {
                this.metrics = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("EssentialProperty")]
        public DescriptorType[] EssentialProperty
        {
            get
            {
                return this.essentialProperty;
            }
            set
            {
                this.essentialProperty = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty
        {
            get
            {
                return this.supplementalProperty;
            }
            set
            {
                this.supplementalProperty = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("UTCTiming")]
        public DescriptorType[] UTCTiming
        {
            get
            {
                return this.uTCTiming;
            }
            set
            {
                this.uTCTiming = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Profiles
        {
            get
            {
                return this.profiles;
            }
            set
            {
                this.profiles = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(PresentationType.@static)]
        public PresentationType Type
        {
            get
            {
                return this.type;
            }
            set
            {
                this.type = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public DateTime AvailabilityStartTime
        {
            get
            {
                return this.availabilityStartTime;
            }
            set
            {
                this.availabilityStartTime = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityStartTimeSpecified
        {
            get
            {
                return this.availabilityStartTimeFieldSpecified;
            }
            set
            {
                this.availabilityStartTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public DateTime AvailabilityEndTime
        {
            get
            {
                return this.availabilityEndTime;
            }
            set
            {
                this.availabilityEndTime = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityEndTimeSpecified
        {
            get
            {
                return this.availabilityEndTimeFieldSpecified;
            }
            set
            {
                this.availabilityEndTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public DateTime PublishTime
        {
            get
            {
                return this.publishTime;
            }
            set
            {
                this.publishTime = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool PublishTimeSpecified
        {
            get
            {
                return this.publishTimeFieldSpecified;
            }
            set
            {
                this.publishTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string MediaPresentationDuration
        {
            get
            {
                return this.mediaPresentationDuration;
            }
            set
            {
                this.mediaPresentationDuration = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string MinimumUpdatePeriod
        {
            get
            {
                return this.minimumUpdatePeriod;
            }
            set
            {
                this.minimumUpdatePeriod = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string MinBufferTime
        {
            get
            {
                return this.minBufferTime;
            }
            set
            {
                this.minBufferTime = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string TimeShiftBufferDepth
        {
            get
            {
                return this.timeShiftBufferDepth;
            }
            set
            {
                this.timeShiftBufferDepth = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string SuggestedPresentationDelay
        {
            get
            {
                return this.suggestedPresentationDelay;
            }
            set
            {
                this.suggestedPresentationDelay = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string MaxSegmentDuration
        {
            get
            {
                return this.maxSegmentDuration;
            }
            set
            {
                this.maxSegmentDuration = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string MaxSubsegmentDuration
        {
            get
            {
                return this.maxSubsegmentDuration;
            }
            set
            {
                this.maxSubsegmentDuration = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class ProgramInformationType
    {

        private string title;

        private string source;

        private string copyright;

        private System.Xml.XmlElement[] any;

        private string lang;

        private string moreInformationURL;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.title;
            }
            set
            {
                this.title = value;
            }
        }

        /// <remarks/>
        public string Source
        {
            get
            {
                return this.source;
            }
            set
            {
                this.source = value;
            }
        }

        /// <remarks/>
        public string Copyright
        {
            get
            {
                return this.copyright;
            }
            set
            {
                this.copyright = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "language")]
        public string Lang
        {
            get
            {
                return this.lang;
            }
            set
            {
                this.lang = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string MoreInformationURL
        {
            get
            {
                return this.moreInformationURL;
            }
            set
            {
                this.moreInformationURL = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class RangeType
    {

        private string starttime;

        private string duration;

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string Starttime
        {
            get
            {
                return this.starttime;
            }
            set
            {
                this.starttime = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class MetricsType
    {

        private DescriptorType[] reporting;

        private RangeType[] range;

        private System.Xml.XmlElement[] any;

        private string metrics;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlElementAttribute("Reporting")]
        public DescriptorType[] Reporting
        {
            get
            {
                return this.reporting;
            }
            set
            {
                this.reporting = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Range")]
        public RangeType[] Range
        {
            get
            {
                return this.range;
            }
            set
            {
                this.range = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Metrics
        {
            get
            {
                return this.metrics;
            }
            set
            {
                this.metrics = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class DescriptorType
    {

        private System.Xml.XmlElement[] any;

        private string schemeIdUri;

        private string value;

        private string id;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string SchemeIdUri
        {
            get
            {
                return this.schemeIdUri;
            }
            set
            {
                this.schemeIdUri = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                this.value = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SubsetType
    {

        private uint[] contains;

        private string id;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint[] Contains
        {
            get
            {
                return this.contains;
            }
            set
            {
                this.contains = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class ContentComponentType
    {

        private DescriptorType[] accessibility;

        private DescriptorType[] role;

        private DescriptorType[] rating;

        private DescriptorType[] viewpoint;

        private System.Xml.XmlElement[] any;

        private uint id;

        private bool idFieldSpecified;

        private string lang;

        private string contentType;

        private string par;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlElementAttribute("Accessibility")]
        public DescriptorType[] Accessibility
        {
            get
            {
                return this.accessibility;
            }
            set
            {
                this.accessibility = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Role")]
        public DescriptorType[] Role
        {
            get
            {
                return this.role;
            }
            set
            {
                this.role = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Rating")]
        public DescriptorType[] Rating
        {
            get
            {
                return this.rating;
            }
            set
            {
                this.rating = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Viewpoint")]
        public DescriptorType[] Viewpoint
        {
            get
            {
                return this.viewpoint;
            }
            set
            {
                this.viewpoint = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "language")]
        public string Lang
        {
            get
            {
                return this.lang;
            }
            set
            {
                this.lang = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ContentType
        {
            get
            {
                return this.contentType;
            }
            set
            {
                this.contentType = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Par
        {
            get
            {
                return this.par;
            }
            set
            {
                this.par = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [XmlIncludeAttribute(typeof(SubRepresentationType))]
    [XmlIncludeAttribute(typeof(RepresentationType))]
    [XmlIncludeAttribute(typeof(AdaptationSetType))]
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class RepresentationBaseType
    {

        private DescriptorType[] framePacking;

        private DescriptorType[] audioChannelConfiguration;

        private DescriptorType[] contentProtection;

        private DescriptorType[] essentialProperty;

        private DescriptorType[] supplementalProperty;

        private EventStreamType[] inbandEventStream;

        private System.Xml.XmlElement[] any;

        private string profiles;

        private uint width;

        private bool widthFieldSpecified;

        private uint height;

        private bool heightFieldSpecified;

        private string sar;

        private string frameRate;

        private string audioSamplingRate;

        private string mimeType;

        private string segmentProfiles;

        private string codecs;

        private double maximumSAPPeriod;

        private bool maximumSAPPeriodFieldSpecified;

        private uint startWithSAP;

        private bool startWithSAPFieldSpecified;

        private double maxPlayoutRate;

        private bool maxPlayoutRateFieldSpecified;

        private bool codingDependency;

        private bool codingDependencyFieldSpecified;

        private VideoScanType scanType;

        private bool scanTypeFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlElementAttribute("FramePacking")]
        public DescriptorType[] FramePacking
        {
            get
            {
                return this.framePacking;
            }
            set
            {
                this.framePacking = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("AudioChannelConfiguration")]
        public DescriptorType[] AudioChannelConfiguration
        {
            get
            {
                return this.audioChannelConfiguration;
            }
            set
            {
                this.audioChannelConfiguration = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("ContentProtection")]
        public DescriptorType[] ContentProtection
        {
            get
            {
                return this.contentProtection;
            }
            set
            {
                this.contentProtection = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("EssentialProperty")]
        public DescriptorType[] EssentialProperty
        {
            get
            {
                return this.essentialProperty;
            }
            set
            {
                this.essentialProperty = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty
        {
            get
            {
                return this.supplementalProperty;
            }
            set
            {
                this.supplementalProperty = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("InbandEventStream")]
        public EventStreamType[] InbandEventStream
        {
            get
            {
                return this.inbandEventStream;
            }
            set
            {
                this.inbandEventStream = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Profiles
        {
            get
            {
                return this.profiles;
            }
            set
            {
                this.profiles = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Width
        {
            get
            {
                return this.width;
            }
            set
            {
                this.width = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool WidthSpecified
        {
            get
            {
                return this.widthFieldSpecified;
            }
            set
            {
                this.widthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Height
        {
            get
            {
                return this.height;
            }
            set
            {
                this.height = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool HeightSpecified
        {
            get
            {
                return this.heightFieldSpecified;
            }
            set
            {
                this.heightFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Sar
        {
            get
            {
                return this.sar;
            }
            set
            {
                this.sar = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string FrameRate
        {
            get
            {
                return this.frameRate;
            }
            set
            {
                this.frameRate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string AudioSamplingRate
        {
            get
            {
                return this.audioSamplingRate;
            }
            set
            {
                this.audioSamplingRate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MimeType
        {
            get
            {
                return this.mimeType;
            }
            set
            {
                this.mimeType = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string SegmentProfiles
        {
            get
            {
                return this.segmentProfiles;
            }
            set
            {
                this.segmentProfiles = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Codecs
        {
            get
            {
                return this.codecs;
            }
            set
            {
                this.codecs = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double MaximumSAPPeriod
        {
            get
            {
                return this.maximumSAPPeriod;
            }
            set
            {
                this.maximumSAPPeriod = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MaximumSAPPeriodSpecified
        {
            get
            {
                return this.maximumSAPPeriodFieldSpecified;
            }
            set
            {
                this.maximumSAPPeriodFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint StartWithSAP
        {
            get
            {
                return this.startWithSAP;
            }
            set
            {
                this.startWithSAP = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool StartWithSAPSpecified
        {
            get
            {
                return this.startWithSAPFieldSpecified;
            }
            set
            {
                this.startWithSAPFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double MaxPlayoutRate
        {
            get
            {
                return this.maxPlayoutRate;
            }
            set
            {
                this.maxPlayoutRate = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MaxPlayoutRateSpecified
        {
            get
            {
                return this.maxPlayoutRateFieldSpecified;
            }
            set
            {
                this.maxPlayoutRateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public bool CodingDependency
        {
            get
            {
                return this.codingDependency;
            }
            set
            {
                this.codingDependency = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool CodingDependencySpecified
        {
            get
            {
                return this.codingDependencyFieldSpecified;
            }
            set
            {
                this.codingDependencyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public VideoScanType ScanType
        {
            get
            {
                return this.scanType;
            }
            set
            {
                this.scanType = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool ScanTypeSpecified
        {
            get
            {
                return this.scanTypeFieldSpecified;
            }
            set
            {
                this.scanTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class EventStreamType
    {

        private EventType[] @event;

        private System.Xml.XmlElement[] any;

        private string href;

        private actuateType actuate;

        private string schemeIdUri;

        private string value;

        private uint timescale;

        private bool timescaleFieldSpecified;

        public EventStreamType()
        {
            this.actuate = actuateType.onRequest;
        }

        /// <remarks/>
        [XmlElementAttribute("Event")]
        public EventType[] Event
        {
            get
            {
                return this.@event;
            }
            set
            {
                this.@event = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string Href
        {
            get
            {
                return this.href;
            }
            set
            {
                this.href = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        [DefaultValueAttribute(actuateType.onRequest)]
        public actuateType Actuate
        {
            get
            {
                return this.actuate;
            }
            set
            {
                this.actuate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string SchemeIdUri
        {
            get
            {
                return this.schemeIdUri;
            }
            set
            {
                this.schemeIdUri = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                this.value = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Timescale
        {
            get
            {
                return this.timescale;
            }
            set
            {
                this.timescale = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TimescaleSpecified
        {
            get
            {
                return this.timescaleFieldSpecified;
            }
            set
            {
                this.timescaleFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class EventType
    {

        private System.Xml.XmlElement[] any;

        private ulong presentationTime;

        private ulong duration;

        private bool durationFieldSpecified;

        private uint id;

        private bool idFieldSpecified;

        private string messageData;

        private System.Xml.XmlAttribute[] anyAttr;

        public EventType()
        {
            this.presentationTime = ((ulong)(0m));
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(typeof(ulong), "0")]
        public ulong PresentationTime
        {
            get
            {
                return this.presentationTime;
            }
            set
            {
                this.presentationTime = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ulong Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool DurationSpecified
        {
            get
            {
                return this.durationFieldSpecified;
            }
            set
            {
                this.durationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MessageData
        {
            get
            {
                return this.messageData;
            }
            set
            {
                this.messageData = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace = "http://www.w3.org/1999/xlink")]
    public enum actuateType
    {

        /// <remarks/>
        onLoad,

        /// <remarks/>
        onRequest,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public enum VideoScanType
    {

        /// <remarks/>
        progressive,

        /// <remarks/>
        interlaced,

        /// <remarks/>
        unknown,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SubRepresentationType : RepresentationBaseType
    {

        private uint level;

        private bool levelFieldSpecified;

        private uint[] dependencyLevel;

        private uint bandwidth;

        private bool bandwidthFieldSpecified;

        private string[] contentComponent;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Level
        {
            get
            {
                return this.level;
            }
            set
            {
                this.level = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool LevelSpecified
        {
            get
            {
                return this.levelFieldSpecified;
            }
            set
            {
                this.levelFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint[] DependencyLevel
        {
            get
            {
                return this.dependencyLevel;
            }
            set
            {
                this.dependencyLevel = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Bandwidth
        {
            get
            {
                return this.bandwidth;
            }
            set
            {
                this.bandwidth = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool BandwidthSpecified
        {
            get
            {
                return this.bandwidthFieldSpecified;
            }
            set
            {
                this.bandwidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string[] ContentComponent
        {
            get
            {
                return this.contentComponent;
            }
            set
            {
                this.contentComponent = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class RepresentationType : RepresentationBaseType
    {

        private BaseURLType[] baseURL;

        private SubRepresentationType[] subRepresentation;

        private SegmentBaseType segmentBase;

        private SegmentListType segmentList;

        private SegmentTemplateType segmentTemplate;

        private string id;

        private uint bandwidth;

        private uint qualityRanking;

        private bool qualityRankingFieldSpecified;

        private string[] dependencyId;

        private string[] mediaStreamStructureId;

        /// <remarks/>
        [XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL
        {
            get
            {
                return this.baseURL;
            }
            set
            {
                this.baseURL = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("SubRepresentation")]
        public SubRepresentationType[] SubRepresentation
        {
            get
            {
                return this.subRepresentation;
            }
            set
            {
                this.subRepresentation = value;
            }
        }

        /// <remarks/>
        public SegmentBaseType SegmentBase
        {
            get
            {
                return this.segmentBase;
            }
            set
            {
                this.segmentBase = value;
            }
        }

        /// <remarks/>
        public SegmentListType SegmentList
        {
            get
            {
                return this.segmentList;
            }
            set
            {
                this.segmentList = value;
            }
        }

        /// <remarks/>
        public SegmentTemplateType SegmentTemplate
        {
            get
            {
                return this.segmentTemplate;
            }
            set
            {
                this.segmentTemplate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Bandwidth
        {
            get
            {
                return this.bandwidth;
            }
            set
            {
                this.bandwidth = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint QualityRanking
        {
            get
            {
                return this.qualityRanking;
            }
            set
            {
                this.qualityRanking = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool QualityRankingSpecified
        {
            get
            {
                return this.qualityRankingFieldSpecified;
            }
            set
            {
                this.qualityRankingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string[] DependencyId
        {
            get
            {
                return this.dependencyId;
            }
            set
            {
                this.dependencyId = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string[] MediaStreamStructureId
        {
            get
            {
                return this.mediaStreamStructureId;
            }
            set
            {
                this.mediaStreamStructureId = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class BaseURLType
    {

        private string serviceLocation;

        private string byteRange;

        private double availabilityTimeOffset;

        private bool availabilityTimeOffsetFieldSpecified;

        private bool availabilityTimeComplete;

        private bool availabilityTimeCompleteFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttr;

        private string value;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ServiceLocation
        {
            get
            {
                return this.serviceLocation;
            }
            set
            {
                this.serviceLocation = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ByteRange
        {
            get
            {
                return this.byteRange;
            }
            set
            {
                this.byteRange = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double AvailabilityTimeOffset
        {
            get
            {
                return this.availabilityTimeOffset;
            }
            set
            {
                this.availabilityTimeOffset = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityTimeOffsetSpecified
        {
            get
            {
                return this.availabilityTimeOffsetFieldSpecified;
            }
            set
            {
                this.availabilityTimeOffsetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public bool AvailabilityTimeComplete
        {
            get
            {
                return this.availabilityTimeComplete;
            }
            set
            {
                this.availabilityTimeComplete = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityTimeCompleteSpecified
        {
            get
            {
                return this.availabilityTimeCompleteFieldSpecified;
            }
            set
            {
                this.availabilityTimeCompleteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute(DataType = "anyURI")]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                this.value = value;
            }
        }
    }

    /// <remarks/>
    [XmlIncludeAttribute(typeof(MultipleSegmentBaseType))]
    [XmlIncludeAttribute(typeof(SegmentTemplateType))]
    [XmlIncludeAttribute(typeof(SegmentListType))]
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentBaseType
    {

        private URLType initialization;

        private URLType representationIndex;

        private System.Xml.XmlElement[] any;

        private uint timescale;

        private bool timescaleFieldSpecified;

        private ulong presentationTimeOffset;

        private bool presentationTimeOffsetFieldSpecified;

        private string indexRange;

        private bool indexRangeExact;

        private double availabilityTimeOffset;

        private bool availabilityTimeOffsetFieldSpecified;

        private bool availabilityTimeComplete;

        private bool availabilityTimeCompleteFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttr;

        public SegmentBaseType()
        {
            this.indexRangeExact = false;
        }

        /// <remarks/>
        public URLType Initialization
        {
            get
            {
                return this.initialization;
            }
            set
            {
                this.initialization = value;
            }
        }

        /// <remarks/>
        public URLType RepresentationIndex
        {
            get
            {
                return this.representationIndex;
            }
            set
            {
                this.representationIndex = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Timescale
        {
            get
            {
                return this.timescale;
            }
            set
            {
                this.timescale = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TimescaleSpecified
        {
            get
            {
                return this.timescaleFieldSpecified;
            }
            set
            {
                this.timescaleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ulong PresentationTimeOffset
        {
            get
            {
                return this.presentationTimeOffset;
            }
            set
            {
                this.presentationTimeOffset = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool PresentationTimeOffsetSpecified
        {
            get
            {
                return this.presentationTimeOffsetFieldSpecified;
            }
            set
            {
                this.presentationTimeOffsetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string IndexRange
        {
            get
            {
                return this.indexRange;
            }
            set
            {
                this.indexRange = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(false)]
        public bool IndexRangeExact
        {
            get
            {
                return this.indexRangeExact;
            }
            set
            {
                this.indexRangeExact = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double AvailabilityTimeOffset
        {
            get
            {
                return this.availabilityTimeOffset;
            }
            set
            {
                this.availabilityTimeOffset = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityTimeOffsetSpecified
        {
            get
            {
                return this.availabilityTimeOffsetFieldSpecified;
            }
            set
            {
                this.availabilityTimeOffsetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public bool AvailabilityTimeComplete
        {
            get
            {
                return this.availabilityTimeComplete;
            }
            set
            {
                this.availabilityTimeComplete = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AvailabilityTimeCompleteSpecified
        {
            get
            {
                return this.availabilityTimeCompleteFieldSpecified;
            }
            set
            {
                this.availabilityTimeCompleteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class URLType
    {

        private System.Xml.XmlElement[] any;

        private string sourceURL;

        private string range;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string SourceURL
        {
            get
            {
                return this.sourceURL;
            }
            set
            {
                this.sourceURL = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Range
        {
            get
            {
                return this.range;
            }
            set
            {
                this.range = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [XmlIncludeAttribute(typeof(SegmentTemplateType))]
    [XmlIncludeAttribute(typeof(SegmentListType))]
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class MultipleSegmentBaseType : SegmentBaseType
    {

        private SegmentTimelineType segmentTimeline;

        private URLType bitstreamSwitching;

        private uint duration;

        private bool durationFieldSpecified;

        private uint startNumber;

        private bool startNumberFieldSpecified;

        /// <remarks/>
        public SegmentTimelineType SegmentTimeline
        {
            get
            {
                return this.segmentTimeline;
            }
            set
            {
                this.segmentTimeline = value;
            }
        }

        /// <remarks/>
        public URLType BitstreamSwitching
        {
            get
            {
                return this.bitstreamSwitching;
            }
            set
            {
                this.bitstreamSwitching = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool DurationSpecified
        {
            get
            {
                return this.durationFieldSpecified;
            }
            set
            {
                this.durationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint StartNumber
        {
            get
            {
                return this.startNumber;
            }
            set
            {
                this.startNumber = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool StartNumberSpecified
        {
            get
            {
                return this.startNumberFieldSpecified;
            }
            set
            {
                this.startNumberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTimelineType
    {

        private SegmentTimelineTypeS[] s;

        private System.Xml.XmlElement[] any;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlElementAttribute("S")]
        public SegmentTimelineTypeS[] S
        {
            get
            {
                return this.s;
            }
            set
            {
                this.s = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTimelineTypeS
    {

        private ulong t;

        private bool tFieldSpecified;

        private ulong n;

        private bool nFieldSpecified;

        private ulong d;

        private string r;

        private System.Xml.XmlAttribute[] anyAttr;

        public SegmentTimelineTypeS()
        {
            this.r = "0";
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ulong T
        {
            get
            {
                return this.t;
            }
            set
            {
                this.t = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TSpecified
        {
            get
            {
                return this.tFieldSpecified;
            }
            set
            {
                this.tFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ulong N
        {
            get
            {
                return this.n;
            }
            set
            {
                this.n = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool NSpecified
        {
            get
            {
                return this.nFieldSpecified;
            }
            set
            {
                this.nFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ulong D
        {
            get
            {
                return this.d;
            }
            set
            {
                this.d = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        [DefaultValueAttribute("0")]
        public string R
        {
            get
            {
                return this.r;
            }
            set
            {
                this.r = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTemplateType : MultipleSegmentBaseType
    {

        private string media;

        private string index;

        private string initialization;

        private string bitstreamSwitching;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Media
        {
            get
            {
                return this.media;
            }
            set
            {
                this.media = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Index
        {
            get
            {
                return this.index;
            }
            set
            {
                this.index = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Initialization
        {
            get
            {
                return this.initialization;
            }
            set
            {
                this.initialization = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string BitstreamSwitching
        {
            get
            {
                return this.bitstreamSwitching;
            }
            set
            {
                this.bitstreamSwitching = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentListType : MultipleSegmentBaseType
    {

        private SegmentURLType[] segmentURL;

        private string href;

        private actuateType actuate;

        public SegmentListType()
        {
            this.actuate = actuateType.onRequest;
        }

        /// <remarks/>
        [XmlElementAttribute("SegmentURL")]
        public SegmentURLType[] SegmentURL
        {
            get
            {
                return this.segmentURL;
            }
            set
            {
                this.segmentURL = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string Href
        {
            get
            {
                return this.href;
            }
            set
            {
                this.href = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        [DefaultValueAttribute(actuateType.onRequest)]
        public actuateType Actuate
        {
            get
            {
                return this.actuate;
            }
            set
            {
                this.actuate = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentURLType
    {

        private System.Xml.XmlElement[] any;

        private string media;

        private string mediaRange;

        private string index;

        private string indexRange;

        private System.Xml.XmlAttribute[] anyAttr;

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string Media
        {
            get
            {
                return this.media;
            }
            set
            {
                this.media = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MediaRange
        {
            get
            {
                return this.mediaRange;
            }
            set
            {
                this.mediaRange = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string Index
        {
            get
            {
                return this.index;
            }
            set
            {
                this.index = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string IndexRange
        {
            get
            {
                return this.indexRange;
            }
            set
            {
                this.indexRange = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class AdaptationSetType : RepresentationBaseType
    {

        private DescriptorType[] accessibility;

        private DescriptorType[] role;

        private DescriptorType[] rating;

        private DescriptorType[] viewpoint;

        private ContentComponentType[] contentComponent;

        private BaseURLType[] baseURL;

        private SegmentBaseType segmentBase;

        private SegmentListType segmentList;

        private SegmentTemplateType segmentTemplate;

        private RepresentationType[] representation;

        private string href;

        private actuateType actuate;

        private uint id;

        private bool idFieldSpecified;

        private uint group;

        private bool groupFieldSpecified;

        private string lang;

        private string contentType;

        private string par;

        private uint minBandwidth;

        private bool minBandwidthFieldSpecified;

        private uint maxBandwidth;

        private bool maxBandwidthFieldSpecified;

        private uint minWidth;

        private bool minWidthFieldSpecified;

        private uint maxWidth;

        private bool maxWidthFieldSpecified;

        private uint minHeight;

        private bool minHeightFieldSpecified;

        private uint maxHeight;

        private bool maxHeightFieldSpecified;

        private string minFrameRate;

        private string maxFrameRate;

        private string segmentAlignment;

        private string subsegmentAlignment;

        private uint subsegmentStartsWithSAP;

        private bool bitstreamSwitching;

        private bool bitstreamSwitchingFieldSpecified;

        public AdaptationSetType()
        {
            this.actuate = actuateType.onRequest;
            this.segmentAlignment = "false";
            this.subsegmentAlignment = "false";
            this.subsegmentStartsWithSAP = ((uint)(0));
        }

        /// <remarks/>
        [XmlElementAttribute("Accessibility")]
        public DescriptorType[] Accessibility
        {
            get
            {
                return this.accessibility;
            }
            set
            {
                this.accessibility = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Role")]
        public DescriptorType[] Role
        {
            get
            {
                return this.role;
            }
            set
            {
                this.role = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Rating")]
        public DescriptorType[] Rating
        {
            get
            {
                return this.rating;
            }
            set
            {
                this.rating = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Viewpoint")]
        public DescriptorType[] Viewpoint
        {
            get
            {
                return this.viewpoint;
            }
            set
            {
                this.viewpoint = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("ContentComponent")]
        public ContentComponentType[] ContentComponent
        {
            get
            {
                return this.contentComponent;
            }
            set
            {
                this.contentComponent = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL
        {
            get
            {
                return this.baseURL;
            }
            set
            {
                this.baseURL = value;
            }
        }

        /// <remarks/>
        public SegmentBaseType SegmentBase
        {
            get
            {
                return this.segmentBase;
            }
            set
            {
                this.segmentBase = value;
            }
        }

        /// <remarks/>
        public SegmentListType SegmentList
        {
            get
            {
                return this.segmentList;
            }
            set
            {
                this.segmentList = value;
            }
        }

        /// <remarks/>
        public SegmentTemplateType SegmentTemplate
        {
            get
            {
                return this.segmentTemplate;
            }
            set
            {
                this.segmentTemplate = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Representation")]
        public RepresentationType[] Representation
        {
            get
            {
                return this.representation;
            }
            set
            {
                this.representation = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string Href
        {
            get
            {
                return this.href;
            }
            set
            {
                this.href = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        [DefaultValueAttribute(actuateType.onRequest)]
        public actuateType Actuate
        {
            get
            {
                return this.actuate;
            }
            set
            {
                this.actuate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint Group
        {
            get
            {
                return this.group;
            }
            set
            {
                this.group = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool GroupSpecified
        {
            get
            {
                return this.groupFieldSpecified;
            }
            set
            {
                this.groupFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "language")]
        public string Lang
        {
            get
            {
                return this.lang;
            }
            set
            {
                this.lang = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ContentType
        {
            get
            {
                return this.contentType;
            }
            set
            {
                this.contentType = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Par
        {
            get
            {
                return this.par;
            }
            set
            {
                this.par = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MinBandwidth
        {
            get
            {
                return this.minBandwidth;
            }
            set
            {
                this.minBandwidth = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MinBandwidthSpecified
        {
            get
            {
                return this.minBandwidthFieldSpecified;
            }
            set
            {
                this.minBandwidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MaxBandwidth
        {
            get
            {
                return this.maxBandwidth;
            }
            set
            {
                this.maxBandwidth = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MaxBandwidthSpecified
        {
            get
            {
                return this.maxBandwidthFieldSpecified;
            }
            set
            {
                this.maxBandwidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MinWidth
        {
            get
            {
                return this.minWidth;
            }
            set
            {
                this.minWidth = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MinWidthSpecified
        {
            get
            {
                return this.minWidthFieldSpecified;
            }
            set
            {
                this.minWidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MaxWidth
        {
            get
            {
                return this.maxWidth;
            }
            set
            {
                this.maxWidth = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MaxWidthSpecified
        {
            get
            {
                return this.maxWidthFieldSpecified;
            }
            set
            {
                this.maxWidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MinHeight
        {
            get
            {
                return this.minHeight;
            }
            set
            {
                this.minHeight = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MinHeightSpecified
        {
            get
            {
                return this.minHeightFieldSpecified;
            }
            set
            {
                this.minHeightFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public uint MaxHeight
        {
            get
            {
                return this.maxHeight;
            }
            set
            {
                this.maxHeight = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MaxHeightSpecified
        {
            get
            {
                return this.maxHeightFieldSpecified;
            }
            set
            {
                this.maxHeightFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MinFrameRate
        {
            get
            {
                return this.minFrameRate;
            }
            set
            {
                this.minFrameRate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MaxFrameRate
        {
            get
            {
                return this.maxFrameRate;
            }
            set
            {
                this.maxFrameRate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute("false")]
        public string SegmentAlignment
        {
            get
            {
                return this.segmentAlignment;
            }
            set
            {
                this.segmentAlignment = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute("false")]
        public string SubsegmentAlignment
        {
            get
            {
                return this.subsegmentAlignment;
            }
            set
            {
                this.subsegmentAlignment = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(typeof(uint), "0")]
        public uint SubsegmentStartsWithSAP
        {
            get
            {
                return this.subsegmentStartsWithSAP;
            }
            set
            {
                this.subsegmentStartsWithSAP = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public bool BitstreamSwitching
        {
            get
            {
                return this.bitstreamSwitching;
            }
            set
            {
                this.bitstreamSwitching = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool BitstreamSwitchingSpecified
        {
            get
            {
                return this.bitstreamSwitchingFieldSpecified;
            }
            set
            {
                this.bitstreamSwitchingFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class PeriodType
    {

        private BaseURLType[] baseURL;

        private SegmentBaseType segmentBase;

        private SegmentListType segmentList;

        private SegmentTemplateType segmentTemplate;

        private DescriptorType assetIdentifier;

        private EventStreamType[] eventStream;

        private AdaptationSetType[] adaptationSet;

        private SubsetType[] subset;

        private DescriptorType[] supplementalProperty;

        private System.Xml.XmlElement[] any;

        private string href;

        private actuateType actuate;

        private string id;

        private string start;

        private string duration;

        private bool bitstreamSwitching;

        private System.Xml.XmlAttribute[] anyAttr;

        public PeriodType()
        {
            this.actuate = actuateType.onRequest;
            this.bitstreamSwitching = false;
        }

        /// <remarks/>
        [XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL
        {
            get
            {
                return this.baseURL;
            }
            set
            {
                this.baseURL = value;
            }
        }

        /// <remarks/>
        public SegmentBaseType SegmentBase
        {
            get
            {
                return this.segmentBase;
            }
            set
            {
                this.segmentBase = value;
            }
        }

        /// <remarks/>
        public SegmentListType SegmentList
        {
            get
            {
                return this.segmentList;
            }
            set
            {
                this.segmentList = value;
            }
        }

        /// <remarks/>
        public SegmentTemplateType SegmentTemplate
        {
            get
            {
                return this.segmentTemplate;
            }
            set
            {
                this.segmentTemplate = value;
            }
        }

        /// <remarks/>
        public DescriptorType AssetIdentifier
        {
            get
            {
                return this.assetIdentifier;
            }
            set
            {
                this.assetIdentifier = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("EventStream")]
        public EventStreamType[] EventStream
        {
            get
            {
                return this.eventStream;
            }
            set
            {
                this.eventStream = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("AdaptationSet")]
        public AdaptationSetType[] AdaptationSet
        {
            get
            {
                return this.adaptationSet;
            }
            set
            {
                this.adaptationSet = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Subset")]
        public SubsetType[] Subset
        {
            get
            {
                return this.subset;
            }
            set
            {
                this.subset = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty
        {
            get
            {
                return this.supplementalProperty;
            }
            set
            {
                this.supplementalProperty = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.any;
            }
            set
            {
                this.any = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string Href
        {
            get
            {
                return this.href;
            }
            set
            {
                this.href = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        [DefaultValueAttribute(actuateType.onRequest)]
        public actuateType Actuate
        {
            get
            {
                return this.actuate;
            }
            set
            {
                this.actuate = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string Start
        {
            get
            {
                return this.start;
            }
            set
            {
                this.start = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "duration")]
        public string Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(false)]
        public bool BitstreamSwitching
        {
            get
            {
                return this.bitstreamSwitching;
            }
            set
            {
                this.bitstreamSwitching = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                this.anyAttr = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public enum PresentationType
    {

        /// <remarks/>
        @static,

        /// <remarks/>
        dynamic,
    }
}
